name: PreventSpawnerChange
version: ${project.version}
main: com.nekozouneko.preventSpawnerChange.PreventSpawnerChange
api-version: '1.21'
folia-supported: true
author: RunQ Run
description: "Prevent changing spawners with spawn eggs"

commands:
  preventspawnerchange:
    aliases: [ psc ]
    description: "PreventSpawnerChangeのメインコマンド"
    usage: "/preventspawnerchange reload"
    permission: preventspawnerchange.reload

permissions:
  preventspawnerchange.reload:
    default: op
  preventspawnerchange.bypass:
    default: op