name: PreventSpawnerChange
version: ${project.version}
main: com.nekozouneko.preventSpawnerChange.PreventSpawnerChange
api-version: '1.21'
folia-supported: true
author: RunQ Run
description: "Prevent changing spawners with spawn eggs"
